version: 2
updates:

  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "build(dependency)"
      include: "scope"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(dependency)"
      include: "scope"