name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore "./src/lexicon.sln"

    - name: Build
      run: dotnet build "./src/lexicon.sln" --no-restore

    - name: Test
      run: dotnet test "./src/lexicon.sln" --no-build --verbosity normal
