name: Commit Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Lint commit message
        uses: wagoid/commitlint-github-action@v5

      - name: Check no !fixup commits
        if: ${{ github.event_name == 'pull_request' }}
        uses: 13rac1/block-fixup-merge-action@v2.0.0
