name: Documentation Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'doc/**'  
      - '**.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'doc/**'
      - '**.md'

jobs:
  run-linters:
    name: Documentation check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Markdown lint
        uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: .
          config_file: ".github/markdownlint.yml"

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.30.0
        with:
          config_path: .github/spellcheck.yml 